### ISSUE TITLE
Recurring issues pulling ImageBuilder from CBL Mariner

### ISSUE THREAD

**Issue by lbussell** [dotnet/docker-tools#1148]
CI for Mariner (both 1.0 and 2.0) has been very unreliable lately, frequently requiring multiple retries.

An example of the error pulling ImageBuilder (from [Run 20230621.1](https://dev.azure.com/dnceng/internal/_build/results?buildId=2206441&view=logs&j=09672b09-d26b-526f-af2e-5749ac23daf2&t=8ef912a3-0165-5bc0-5e15-91c0ed7f26cd)). It's a `dotnet-docker-nightly-playground` pipeline run but this is occurring in PR validation as well.

```
Pulling Docker image mcr.microsoft.com/dotnet-buildtools/image-builder:2201245
Error response from daemon: Get "[https://mcr.microsoft.com/v2/"](https://mcr.microsoft.com/v2/%22): context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Retry 1/5 exited 1, retrying in 1 seconds...
Error response from daemon: Get "[https://mcr.microsoft.com/v2/"](https://mcr.microsoft.com/v2/%22): context deadline exceeded
Retry 2/5 exited 1, retrying in 6 seconds...
Error response from daemon: Get "[https://mcr.microsoft.com/v2/"](https://mcr.microsoft.com/v2/%22): context deadline exceeded
Retry 3/5 exited 1, retrying in 36 seconds...
Error response from daemon: Get "[https://mcr.microsoft.com/v2/"](https://mcr.microsoft.com/v2/%22): net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Retry 4/5 exited 1, retrying in 216 seconds...
Error response from daemon: Get "[https://mcr.microsoft.com/v2/"](https://mcr.microsoft.com/v2/%22): net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by mthalman** [comment]
I don't think this is a Mariner thing. This is just MAR. There was a recent mention of this: https://github.com/microsoft/containerregistry/issues/139#issuecomment-1601187932.

**Comment by mthalman** [comment]
[Triage]
There's an active issue with MAR that they're aware of. Nothing related to our Docker infrastructure.
