### ISSUE TITLE
Switch Windows Server 2022 CI pools back to Docker-2022

### ISSUE THREAD

**Issue by lbussell** [dotnet/docker-tools#1164]
In https://github.com/dotnet/docker-tools/pull/1163, we switched from Docker-2022* pools to 1ES hosted pools due to issues with internet connection in containers in the Docker-2022 pools. We should switch back once the incident is resolved.

**Comment by mthalman** [comment]
We've always maintained our own pools so that we can ensure we have a pool for day 1 of the release of a new version of Windows Server. We also use VMs that are tuned to have good performance for our builds.
