### ISSUE TITLE
Microsoft.IdentityModel.Clients.ActiveDirectory is deprecated

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#1176]
Image Builder has a dependency on Microsoft.IdentityModel.Clients.ActiveDirectory which is marked as deprecated. This should be [migrated to use MSAL.NET instead](https://learn.microsoft.com/entra/msal/dotnet/#migration-from-azure-active-directory-authentication-library-adal). This has shown up in the component governance report.

**Comment by mthalman** [comment]
This should take precedence over the work in https://github.com/dotnet/docker-tools/issues/1123.

**Comment by lbussell** [comment]
This now has a hard due date of April 13 2024.

**Comment by lbussell** [comment]
This is blocking ImageBuilder builds since last Friday 03/15/2024 - https://dev.azure.com/dnceng/internal/_build/results?buildId=2405989&view=logs&j=ac422da1-c6cf-5423-8ede-22ab7060639a&t=898b1438-1a8f-5482-ed55-51c989cf5404&l=818

**Comment by lbussell** [comment]
The due date was extended to 04/01/2024.

**Comment by lbussell** [comment]
Related https://github.com/dotnet/dotnet-docker-internal/issues/4648 [internal issue]
