### ISSUE TITLE
Consider removing the image cleanup logic in pipelines

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#1213]
The common pipeline implementation contains logic to cleanup Docker state before and after images are built:
* https://github.com/dotnet/docker-tools/blob/main/eng/common/templates/steps/cleanup-docker-linux.yml
* https://github.com/dotnet/docker-tools/blob/main/eng/common/templates/steps/cleanup-docker-windows.yml

These steps can add a fair amount of execution time, especially on Windows agents. Some recent runs have shown this taking 5 minutes on a Windows agent.

At the time this was implemented, build agents were potentially reused between runs and it was important to keep the state of the agents clean. Since then, however, we're using stateless pools that provide fresh agents each time. So there really isn't much need to clean the agent. The one exception might be for cases where we would run out of disk space. That's most likely to happen in the .NET Framework pipeline.

So, by default, I propose that we eliminate the clean steps. If it's necessary to clean for disk space purposes, this is something that can be opted into.

**Comment by lbussell** [comment]
Removed the majority of the cleanup steps with https://github.com/dotnet/docker-tools/pull/1229.
