### ISSUE TITLE
Factor out default build agent pools and image names into shared variables

### ISSUE THREAD

**Issue by lbussell** [dotnet/docker-tools#1227]
Related: https://github.com/dotnet/dotnet-docker-internal/issues/4475

With the addition of 1ES pipeline templates, we have a few places where our default pool definitions are overridden or ignored. We should consolidate these into one set of variables for our pools and image names so we don't have any hardcoded values anywhere.

https://github.com/dotnet/docker-tools/blob/5a5564806a23862c5a8416477a59c89b30b66b4d/eng/common/templates/stages/dotnet/build-test-publish-repo.yml#L64-L73

https://github.com/dotnet/docker-tools/blob/5a5564806a23862c5a8416477a59c89b30b66b4d/eng/common/templates/variables/common.yml#L46-L57

https://github.com/dotnet/docker-tools/blob/5a5564806a23862c5a8416477a59c89b30b66b4d/eng/pipelines/dotnet-buildtools-image-builder-official.yml#L21-L27

https://github.com/lbussell/dotnet-docker/blob/9482b39dbd103f56ce42b62cbb14bda00f223c40/eng/pipelines/cg-images.yml#L25-L36

**Comment by lbussell** [comment]
1. The `default*PoolImage` variables should stay .NET-independent, and we can continue to use the `/dotnet/build-test-publish-repo.yml` file to define the 1ES PT compliant images. We should however define variables for the SDL scanning pool so that they can be shared between all of our pipelines: https://github.com/dotnet/docker-tools/blob/5a5564806a23862c5a8416477a59c89b30b66b4d/eng/pipelines/dotnet-buildtools-image-builder-official.yml#L21-L27

**Comment by lbussell** [comment]
Marking as wave1 since this is 1ES PT follow-up.

**Comment by ellahathaway** [comment]
I'm continuing to work on this issue. Hoping to have a few PRs out for it soon.

**Comment by ellahathaway** [comment]
https://github.com/microsoft/dotnet-framework-docker/pull/1171 is the last PR needed to close out this issue.
