### ISSUE TITLE
"Post Publish Notification" pipeline step is failing due to changes in Wait For Mcr Ingestion pipeline tasks

### ISSUE THREAD

**Issue by lbussell** [dotnet/docker-tools#1278]
It's giving the following error:

```
Unhandled exception: System.InvalidOperationException: Build task with name 'WaitForImageIngestion' could not be found in the build timeline.
   at Microsoft.DotNet.ImageBuilder.Commands.PostPublishNotificationCommand.GetBuildTaskResultsAsync(Dictionary`2 taskResults, IBuildHttpClient buildClient, TeamProject project) in /image-builder/src/Commands/PostPublishNotificationCommand.cs:line 156
   at Microsoft.DotNet.ImageBuilder.Commands.PostPublishNotificationCommand.ExecuteAsync() in /image-builder/src/Commands/PostPublishNotificationCommand.cs:line 78
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
```

Due to changes from https://github.com/dotnet/docker-tools/pull/1271.

**Comment by lbussell** [comment]
This is still happening even after the following PRs tried to fix it:
- https://github.com/dotnet/docker-tools/pull/1279
- https://github.com/dotnet/docker-tools/pull/1280
- https://github.com/dotnet/docker-tools/pull/1281

Error: https://dev.azure.com/dnceng/internal/_build/results?buildId=2450186&view=logs&j=739bb7ec-7296-5b40-7dff-ee3297bfdaa4&t=487ef77f-c8ee-5b2f-147b-5cff06a12f4e&l=102

```
Unhandled exception: System.InvalidOperationException: Build task with name 'Wait for Mcr Doc Ingestion' could not be found in the build timeline.
```

It is probably time for me to repro and debug this.

**Comment by mthalman** [comment]
It's because of the casing of `MCR` (versus `Mcr`) this time. I missed that with my casing change. But it should be resolved now with the update to make the check case-insensitive.

**Comment by mthalman** [comment]
This makes the pipeline now use the fix to make it case-insensitive: https://github.com/dotnet/docker-tools/pull/1282

**Comment by lbussell** [comment]
This is now failing with another error:

```
- ManagedIdentityCredential authentication unavailable. The requested identity has not been assigned to this resource.
Status: 400 (Bad Request)

Content:
{"error":"invalid_request","error_description":"Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request"}
```

**Comment by mthalman** [comment]
That's a separate issue. The `Post Publish Notification` step issue looks to be [fixed](https://dev.azure.com/dnceng/internal/_build/results?buildId=2451745&view=logs&j=739bb7ec-7296-5b40-7dff-ee3297bfdaa4&t=487ef77f-c8ee-5b2f-147b-5cff06a12f4e) (internal link).

**Comment by lbussell** [comment]
I filed https://github.com/dotnet/docker-tools/issues/1286 for that issue so we can close this as fixed unless it comes up again.
