### ISSUE TITLE
Stop mirroring images that are already on Azure Container Registries

### ISSUE THREAD

**Issue by lbussell** [dotnet/docker-tools#1332]
The `CopyBaseImagesCommand` logic copies images indiscriminately. The intention is for that logic to mirror images that are subject to rate-limiting (i.e. from DockerHub). Some of the images we use are now located in Azure Container Registries by default, like `azurelinuxpreview.azurecr.io` and `ubuntu.azurecr.io`. These should not be mirrored since they are not affected by rate-limiting the same as other images.

**Comment by mthalman** [comment]
This was intentional.

1. It keeps the implementation simple.
1. It ensures that we are unblocked if any of the 3rd party registries are unavailable.
