### ISSUE TITLE
Builds trying to pull Docker Hub images from cache ACR without using `library` repo

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#1341]
Some Dockerfiles in the buildtools-prereqs repo reference the non-architecture-specific repo name (e.g. `fedora:40`). For Docker Hub, there's an implicit `library` repo here (e.g. `library/fedora:40`). The changes from https://github.com/dotnet/docker-tools/pull/1333 correctly mirror those images to a `library` repo in the ACR. But with the changes from https://github.com/dotnet/docker-tools/pull/1338, the build doesn't include `library` in the image name, resulting in an image name that is not found in the registry (see [failed build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=710393&view=logs&j=cad7607d-cfd7-5370-bec9-27905e063bd7&t=cd02762f-7706-5a8a-d45d-fbee9d96e924) (internal link)).

**Comment by lbussell** [comment]
[Triage] This was worked around in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1087. Other repos are not affected. Since this isn't currently causing an issue it's not a priority to fix in docker-tools.
