### ISSUE TITLE
Branch validation can't be overridden

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#1351]
The branch validation logic has an issue that doesn't allow the check to be overridden.

https://github.com/dotnet/docker-tools/blob/eb406de4f0e3bafaebf1026fe206a17880567a17/eng/common/templates/steps/validate-branch.yml#L7-L28

I ran a build from an unofficial branch and set `overrideOfficialBranchValidation` as a variable but I still got the `Official builds must be done from an official branch` error.

**Comment by lbussell** [comment]
This is because the variable is hard-coded into the pipeline:

https://github.com/dotnet/docker-tools/blob/6d3f697c41460c5fbc82bdd7bd477a02ddccb0e2/eng/common/templates/variables/common.yml#L35-L36

It should be removed, since hard-coded variables like that can't be overridden from the UI AFAIK.
