### ISSUE TITLE
Cache misses from differing commit hash leading to unnecessary builds

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#1404]
There are a few Dockerfiles which are not being recognized as a cache hit to an already published version of the image.

From the [build log](https://dev.azure.com/dnceng/internal/_build/results?buildId=2437940&view=logs&j=82bd956b-c002-53af-91ab-cbfb8a43eb9e&t=3a7e4ef4-ed98-5fc0-2e5b-a88f304b7faf) (internal link):

```
Image info's Dockerfile commit: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/507c1c3291de8f64d9592f72ae92f8f9f0b45353/src/ubuntu/22.04/coredeps/Dockerfile
Latest Dockerfile commit: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/70a3638e31ff3f7f69a9373b0b4c06773f5eaee6/src/ubuntu/22.04/coredeps/Dockerfile
Dockerfile commits match: False
CACHE MISS
```

```
Image info's Dockerfile commit: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/3fc5553956a6e28906d81758fc2852c6a1fd93cc/src/ubuntu/18.04/crossdeps/Dockerfile
Latest Dockerfile commit: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/70a3638e31ff3f7f69a9373b0b4c06773f5eaee6/src/ubuntu/18.04/crossdeps/Dockerfile
Dockerfile commits match: False
CACHE MISS
```

```
Image info's Dockerfile commit: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/507c1c3291de8f64d9592f72ae92f8f9f0b45353/src/ubuntu/22.04/coredeps/Dockerfile
Latest Dockerfile commit: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/70a3638e31ff3f7f69a9373b0b4c06773f5eaee6/src/ubuntu/22.04/coredeps/Dockerfile
Dockerfile commits match: False
CACHE MISS
```

These are being detected as being different commit hashes than what Dockerfile was last used to publish. But that's false because the different commit hashes are actually pointing to the same version of the Dockerfile. For example, with that first one (https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/70a3638e31ff3f7f69a9373b0b4c06773f5eaee6/src/ubuntu/22.04/coredeps/Dockerfile), if you go to the URL in your browser, you'll see the webpage refer to that version using the short hash of the equivalent hash:

![image](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/assets/15789599/6a11677d-043b-4c6b-b351-55431953e52a)

It's not clear why there are differences in the values, nor why the publishing process doesn't update the image info JSON content with the value that we're detecting the file to have.

**Comment by lbussell** [comment]
> `git log -1 --format=format:%{format} {filePath}`
> Something must be causing it to retrieve the wrong commit. 

I wonder if this could be due to the pipeline shallow-cloning the repo, if it does that.

**Comment by lbussell** [comment]
[Triage] This seems to cause CBL Mariner images to be rebuilt more frequently then they need to. There are some large builds in that dependency graph. Given that this could be a relatively simple fix, we should definitely invest in the initial investigation here.

**Comment by lbussell** [comment]
[Triage] Related: This might cause issues if we need to move back to a single pipeline due to this issue: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/1186#issuecomment-2310833020

**Comment by mthalman** [comment]
Confirmed this was caused by a shallow fetch of the git repo. This was configured in the AzDO UI for several pipelines. I've set them all to not do any shallow fetch.

**Comment by lbussell** [comment]
Thanks for investigating this @mthalman!
