### ISSUE TITLE
Dependent images are cached and not re-built when their base image's Dockerfile is changed

### ISSUE THREAD

**Issue by lbussell** [dotnet/docker-tools#1516]
See https://github.com/dotnet/dotnet-docker/pull/6110#issuecomment-2536965183

## Steps to reproduce the issue

Queue a PR validation build of dotnet-docker repo where some runtime deps Dockerfiles are changed but not any dependent runtime or aspnet Dockerfiles.

## Expected behavior

All images dependent on the changed runtime-deps images will be re-built.

## Actual behavior

No images dependent on the changed runtime-deps images are re-built. This results in test failures when there is an expected behavior change like in https://github.com/dotnet/dotnet-docker/pull/6110.

**Comment by mthalman** [comment]
This is a regression that was caused by https://github.com/dotnet/docker-tools/pull/1427. That change explicitly prevented it from accounting for locally built base images which is problematic for this scenario.
