### ISSUE TITLE
Make use of Docker.DotNet library

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#153]
Rather than invoking docker CLI directly, ImageBuilder could take a dependency on [Docker.DotNet](https://github.com/microsoft/docker.dotnet) and execute all the Docker client operations in-proc.  This should make things more robust and probably improve performance as well.

**Comment by MichaelSimons** [comment]
I played around with the Docker.DotNet library a little and noted the following concerns.

1. There haven't been any releases of the library for over 2 years now.  The source repo is still active though.  You can read about why there hasn't been any releases [here](https://github.com/dotnet/Docker.DotNet/issues/418).
1. As a result of the previous point, the documentation and the released bits are not in sync.  In general I found the documentation and samples lacking which makes the learning curve steeper than expected.   There are however a number of posted on [StackOverflow](https://stackoverflow.com/)
1. The library is lacking in a number of places IMO.  A good example is around the Docker build context.  The library doesn't have any APIs that will create the context from a local directory - e.g. create a tarball.  This implies there is no support for `.dockerignore` files.  The library user would be responsible for implementing this if desired.

On the positive side, the async APIs were nice and there are cases where the APIs will simplify the ImageBuilder logic (e.g. inspecting images and handling credentials).

**Comment by MichaelSimons** [comment]
Given the state of the library, this is not a viable approach at this time.  Closing.
