### ISSUE TITLE
manifest.json editor tool

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#157]
It'd be nice to have an editor tool, either CLI or GUI, for managing manifest.json files so that hand-editing them is not required.  The more complex they get, the greater chance of introducing errors when making changes by hand.

**Comment by MichaelSimons** [comment]
Nice to have but a low priority item at the moment.

**Comment by MichaelSimons** [comment]
We discussed this and believe there isn't ROI that justifies this work.  We believe it would be rather difficult and costly to produce a tool that would cover all of our use cases.
