### ISSUE TITLE
Image Builder should compute full dependency hierarchy for customBuildLegGrouping

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#175]
When making use of a customBuildLegGrouping in a manifest and referencing it when building a matrix, Image Builder doesn't walk the hierarchy of the dependency images to produce the necessary dependency graph.  For example, lets say my A image has a customBuildLegGrouping dependency on image B and image B depends on image C.  What should happen is that the computed set of Dockerfile paths for image A should include both image B and image C.  But the issue is that it only includes image B.  This can be worked around by explicitly adding image C as a dependency in the customBuildLegGrouping. 

This issue is demonstrated by the 4.6.2 runtime image in [Microsoft/dotnet-framework-docker](https://github.com/Microsoft/dotnet-framework-docker).  It depends on 4.7.1 SDK and 4.7.2 SDK for its pr-build customBuildLegGrouping.  But the corresponding runtime images are not being included automatically.  See https://github.com/Microsoft/dotnet-framework-docker/pull/277.

**Comment by MichaelSimons** [comment]
@mthalman - Was this issue resolved with https://github.com/dotnet/docker-tools/pull/493?  Can this be closed?  If not what is remaining?

**Comment by mthalman** [comment]
> @mthalman Matt Thalman FTE - Was this issue resolved with #493? Can this be closed? If not what is remaining?

Yes, good call.  I forgot I had encountered this issue before.
