### ISSUE TITLE
Refactor PR build pipeline to split build and tests into separate jobs

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/docker-tools#185]
@mthalman commented on [Fri May 10 2019](https://github.com/microsoft/dotnet-framework-docker/issues/283)

Currently the PR build flow ends up executing both the building of dependent images and testing into the same job.  This was done due to not being able to make use of the secrets in order to connect to the ACR since the pipeline is publicly exposed.  There are some workarounds we can explore to resolve this though.

**Comment by mthalman** [comment]
[Triage]
There is no solution available for making use of secrets in public builds which would be necessary to flow images between build jobs.
