### ISSUE TITLE
Auto-update PR with built image tag(s)

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#193]
When a PR is committed it can trigger a build to run (this is currently true for the dotnet/docker-tools and dotnet/dotnet-buildtools-prereqs-docker repos).  That will build the appropriate images and publish them to MCR.  As part of the publishing, a comment should be added to the original PR to indicate the tags of the images for easy retrieval.

**Comment by MichaelSimons** [comment]
This will be covered by https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/69.  Closing as duplicate.
