### ISSUE TITLE
Build and source tagging for release builds

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#197]
It would be worthwhile to add more traceability to the engineering infrastructure so that we can go back and determine the build and commit associated with a particular image.  This would be useful to troubleshoot any issues.  The build provides a lot of diagnostic information and the commit clearly reflects the contents of Dockerfiles so both of these artifacts are useful.

Proposal:
* Add a "tags" variable to official builds that can be set when queued.  This would be set by the person when manually queuing the build or programmatically if the build was queued through automation.  Example of the value that would be set with a comma-delimited set of tags: "3.0-preview6".
* The build pipeline would have a final stage that would tag the build and mark it to be retained indefinitely so that it isn't deleted by the retention policy.  There may be more than one build that gets queued that is associated with a "release"; each one of them should have the same tag (i.e. the cardinality of tags to builds is 1-to-many).
* As part of the build stage, the commit associated with the build would get tagged.  It is done in the build stage because that is the stage where the commit that is used actually determines the "content" of the images that are built.  There may be other builds associated with a release and they could theoretically be using different commits.  But as long as there is only one build stage executed for a release, this should be fine.  Technically, tagging the commit would be optional because you could find the commit associated with the tagged build.  But it would be nice to have the commits tagged appropriately so you could just start from Git if that's where you needed to diagnose something.

**Comment by MichaelSimons** [comment]
The primary scenarios which we know we want to capture information on is to be able to find out easily why a build was triggered.  Was it a release or base image change?  What git commit was the build based on?  What were the image digests produced by the builds?  These scenarios are covered by the [Tag-Details concept](https://github.com/dotnet/dotnet-docker/issues/212).

Tagging the source for each triggered build could result in many tags on a particular commit.  Retaining all triggered builds could also result in large amount of retained builds.  Are these necessary in addition to the Tag-Details?  At this point in time, let's hold off on implementing this until we have a concrete scenario for wanting this data.
