### ISSUE TITLE
Fix tracking of base image digests for multi-stage Dockerfiles

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#205]
Some of our Dockerfiles make use of multi-stage builds and we're tracking the image digests of all the images referenced in the FROM statements.  That means if any of those base images changes, it'll cause a build to be kicked off to rebuild the image.  But we don't actually care about _all_ of those base images.  We only care about the base image of the image _produced_ by the Dockerfile, not the intermediate images that were used during the build process.

We should update Image Builder's Build command to only output the image digest for the "final" base image.

**Comment by MichaelSimons** [comment]
> We should update Image Builder's Build command to only output the image digest for the "final" base image.

I logged https://github.com/dotnet/dotnet-docker/issues/1668 to track this work separately.
