### ISSUE TITLE
Consolidate multiple manifest.json files into one

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/docker-tools#206]
Within the production repos, the samples and production images are stored in separate manifest files (e.g. https://github.com/dotnet/dotnet-docker/blob/master/manifest.json and https://github.com/dotnet/dotnet-docker/blob/master/manifest.samples.json).  The reason this was done was for historical reasons.  Ideally we should be keeping the number of top level files to a minimum to reduce the clutter.  Unfortunately the build infra has a dependency on the fact that there are separate manifests.  For example the samples build simply passes in the samples manifest with no repo filters when it builds.  If the manifests were combined, the builds would need to specify a repo filter.

**Comment by mthalman** [comment]
[Triage]
There's not much of a need for this and doesn't provide any business value at this point.
