### ISSUE TITLE
Migrate pipeline schedules to YAML

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#208]
YAML-based pipelines can now define schedules within the YAML file rather than the UI editor.  In fact, that's the only way to do it.  Pipelines that previously had schedules defined through the UI are grandfathered in though.  We should just update all our pipelines that use schedules to define them in the YAML.

https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/pipelines/sprint-153-update#use-cron-syntax-to-specify-schedules-in-a-yaml-file

- [x] update-dependencies-from-drop
- [x] dotnet-core-size-validation
- [x] dotnet-docker-tools-check-base-image-updates

**Comment by MichaelSimons** [comment]
@mthalman - once https://github.com/dotnet/docker-tools/pull/454 is merged, are there any build definitions left to update?

**Comment by mthalman** [comment]
Nope, that should be it.  Closing.
