### ISSUE TITLE
CopyAcrImages command attempts to import image tags marked as IsLocal

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#244]
When a tag in the manifest is marked as `IsLocal`, it means that tag will not be pushed when running the Build command with the `--push` option.  When the CopyAcrImages command is then executed later on, it needs to then check whether the tag its attempting to import is marked as `IsLocal`.  If it is, that tag won't exist in the source registry; so there's nothing to import.  It should just skip any tags marked as `IsLocal`.  By not skipping such tags, it just causes failures when running the import operation because the tag doesn't exist.

**Comment by MichaelSimons** [comment]
There aren't any usages that encounter this issue today.

**Comment by mthalman** [comment]
[Triage]
This is relevant today because of some Dockerfile patterns that we've wanted to use in the https://github.com/dotnet/dotnet-buildtools-prereqs-docker repo. For example, there was a desire to have a "builder" Dockerfile that would be built locally only and shared by other multi-stage Dockerfiles. But due to limitations like this, it was required to be set with `IsLocal` being `false`.

**Comment by mthalman** [comment]
Local tags are no longer supported.
