### ISSUE TITLE
Add support for categorizing build failures

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/docker-tools#280]
Arcade has support for categorizing build failures.  This is helpful to get a better sense of what types of issues are causing build failures and to identify areas of opportunity to make the builds more reliable.  Right now the majority of failures from the Docker builds are categorized as unknown.

To categorize a failure, the following should get emitted into the build output.

```
echo "##vso[task.logissue type=error](NETCORE_ENGINEERING_TELEMETRY=Publish) Publishing failed with exit code 1."
```

Currently Arcade has the following categories defined - "Restore", "Build", "Test", "Sign", and "InitializeToolset".  Teams are free to define their own as appropriate.  "Build", "Test", and "InitializeToolset" make sense in the Docker context.  "Publish" is the other obvious one for the Docker builds.  We may consider further breakdown such as including a platform variant for each as well.  "Build-Linux-amd64", "Build-Linux-arm64", etc.

See https://github.com/dotnet/arcade/blob/master/Documentation/Projects/DevOps/CI/Telemetry-Guidance.md for more details on the Arcade infra.

**Comment by mthalman** [comment]
[Triage]
Since Arcade isn't being used in the repo, there's little benefit in using this convention because there's no tooling which supports it.
