### ISSUE TITLE
Image info format doesn't separate metadata for multiples images built from the same Dockerfile

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#286]
The [image info](https://github.com/dotnet/versions/blob/eb5a38e95113c07585dab308669f084e492d16dd/build-info/docker/image-info.dotnet-dotnet-docker-master.json#L737) file keys off of the image's Dockerfile folder path.  In the case of the sample projects, there can be a single Dockerfile that is built on multiple platforms, each producing different tags.  So when the image info file gets updated with the metadata from these images, that metadata all goes into the same element since the images all share the same Dockerfile folder path.  This doesn't currently cause any issues with the image dependency flow system because it only looks up the digests for the images that it cares about and ignores the extraneous other data in the image info file.  But from a correctness standpoint, the metadata contained in the image info file should be separated properly.

**Comment by MichaelSimons** [comment]
Fixed with #437.
