### ISSUE TITLE
Publishing of .NET Core Sample images causes multiple redundant image imports in ACR

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#293]
Since the .NET Core Sample images are all built off the same Dockerfile, it causes the image info data generated during the build to have multiple tags from distinct images all associated with one image path.  When this image info is passed to the CopyAcrImagesCommand, it causes it to make multiple import requests for the same tag.  This is because it enumerates the images that are to be published and then looks up the tags associated with those images. For each image it enumerates, it finds all of the tags (not just the tag for that image).

This is related to #286.  It's debatable whether this should even be a separate bug compared to #286 since the fix for this would just be a workaround for #286.

**Comment by MichaelSimons** [comment]
Fixed with #437.
