### ISSUE TITLE
Allow multiple pipeline stages to be explicitly defined to run

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#295]
Currently the pipeline template allows either all stages to be run or a single stage to be run.  This is based off the `singlePhase` parameter.  If left blank, it runs everything; if it's set, it runs the specified stage.  The parameter should be changed to take a list of stages that can be executed rather than just a single one.  This would be useful for .NET Core releases where we pre-build the images prior to tic-toc but then need to test and publish; it would be good to run test and publish in one build.

**Comment by MichaelSimons** [comment]
@mthalman - please investigate the feasibility of this with given the current stages implementation.  At one time I had investigated this and determined the ROI wasn't worthwhile.

**Comment by mthalman** [comment]
My initial testing shows that this is definitely feasible without a lot of work.  It certainly adds a few more conditions to the test and publish stages but nothing that gets too out of hand.

**Comment by MichaelSimons** [comment]
@mthalman - I'm curious what your basic approach is.

**Comment by mthalman** [comment]
@MichaelSimons - Figured it was easier to make a PR rather than explain it: #324
