### ISSUE TITLE
Create a build definition that will push the shared eng/common infra to the consuming repos whenever changes are made

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/docker-tools#313]
The build definition should invoke the [FilePusher](https://github.com/dotnet/docker-tools/tree/master/eng/file-pusher) utility to create the PRs in the consuming repos.  Ideally this build definition would run automatically whenever there are changes to the eng/common folder.

**Comment by mthalman** [comment]
Fixed by #321
