### ISSUE TITLE
Factor out MCR-specific commands from Image Builder

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#351]
The `GenerateTagsReadme` and `PublishMcrDocs` commands are MCR-specific and would not apply to organizations outside of Microsoft that want to make use of Image Builder.  These should be factored out into a separate tool intended just for Docker image publishers within Microsoft.

**Comment by MichaelSimons** [comment]
Closing as making ImageBuilder a general purpose tool is not a business priority.  Addressing this would not add value to the .NET usage of the tool.
