### ISSUE TITLE
Remove .NET repo-specific defaults for command options

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#352]
Default values for command options that are specific to the .NET-owned repos should be removed.  These are poor default values because they wouldn't apply to consumers of Image Builder outside the .NET team.  An example of this is: https://github.com/dotnet/docker-tools/blob/1c784eecbe003818b0b64ab42553e6b2291a67a3/src/Microsoft.DotNet.ImageBuilder/src/Commands/GitOptions.cs#L86

**Comment by MichaelSimons** [comment]
The GitOptions are no longer defaulted to .NET owned repos.  I checked the rest of the options and didn't see any .NET specific defaults.  Closing.
