### ISSUE TITLE
Update Image Builder tool for general purposes

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#353]
The intention is for Image Builder to be a tool that can be used by many teams/products/organizations that produce Docker images.  There are several characteristics it has that make it not so suitable outside the context of the .NET team.  This epic tracks these issues.

**Comment by MichaelSimons** [comment]
Making a general purpose tool is not a business priority at this point.  As a design principle we should strive to keep the tool abstract and not couple it to the .NET usage.  Other teams should be able to use the tool to build their Docker images.  There are certain assumption that should be made in favor of keeping the investments reasonable.  An example of this would be the assumption the tool has on the Dockerfile paths in specialized commands like GenerateBuildMatrix.
