### ISSUE TITLE
Generalize output of `GenerateBuildMatrix` command

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#354]
The `GenerateBuildMatrix` command produces output that is specific to Azure DevOps pipeline's matrix format.  This should be generalized to allow for consumption of Image Builder in other CI/CD environments.  This isn't to say there needs to be an implementation of all those CI/CD providers formats.  Rather, there should be something like a provider model that can allow for additional formats to be implemented by consumers.

**Comment by MichaelSimons** [comment]
Closing as making ImageBuilder a general purpose tool is not a business priority.  Addressing this would not add value to the .NET usage of the tool.
