### ISSUE TITLE
Image Builder should adopt semantic versioning

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#355]
Consumers of Image Builder should be able to easily know whether a new version of the tool has new functionality or contains a breaking change.  Currently that status is unknown.  Each new build of the Image Builder Docker image has a unique timestamp-based tag which provides no indication of compatibility.  To solve this, Image Builder should adopt semantic versioning.

**Comment by MichaelSimons** [comment]
Closing as making ImageBuilder a general purpose tool is not a business priority.  Addressing this would not add value to the .NET usage of the tool.
