### ISSUE TITLE
Factor out Image Builder logic and redesign API to be outside the context of any CLI

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#356]
The logic contained in Image Builder should be factored in such a way to separate it from the CLI interface.  That is, each command's logic should be redesigned into it's own API that doesn't necessarily need to follow the API of the CLI command/options pattern.  This logic should then be factored out into its own library that can be consumed as a standalone library.  The CLI project can then reference this library, wrapping its logic with the command/options pattern.

This factoring may include multiple layers.  For example, it would be nice to factor out useful logic which doesn't rely on the manifest into its own API so that it could be used independently of a manifest.

**Comment by mthalman** [comment]
This is somewhat related to https://github.com/dotnet/docker-tools/issues/314.  But more so than just factoring out into a separate library, the main intent here is to actually redesign the API as part of that factoring.  I've clarified the issue title to more accurately represent that intent.

**Comment by MichaelSimons** [comment]
Closing as making ImageBuilder a general purpose tool is not a business priority.  Addressing this would not add value to the .NET usage of the tool.
