### ISSUE TITLE
Factor out dependency on .NET Dockerfile path pattern

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#357]
The `GenerateBuildMatrix` command has a hard dependency on knowing the pattern of how Dockerfiles folders are arranged in the .NET repos.

Exhibit A: https://github.com/dotnet/docker-tools/blob/1c784eecbe003818b0b64ab42553e6b2291a67a3/src/Microsoft.DotNet.ImageBuilder/src/Commands/GenerateBuildMatrixCommand.cs#L124

This prevents this command from being used in contexts that don't follow this folder pattern.  It should be generalized in a way that allows it to support whatever folder structure a repo has.

**Comment by MichaelSimons** [comment]
Closing as making ImageBuilder a general purpose tool is not a business priority.  Addressing this would not add value to the .NET usage of the tool.
