### ISSUE TITLE
Remove customBuildLegGrouping from manifest schema

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#359]
The manifest schema currently has the concept of specifying a `customBuildLegGrouping` for a platform.  This concept is purely specific to the generation of a build matrix and doesn't really fit well in the manifest which is intended to be metadata about the images.  Since `customBuildLegGrouping` is really a concept meant just for the the `generateBuildMatrix` command, it should be factored out of the manifest into a separate file.

**Comment by MichaelSimons** [comment]
Closing as making ImageBuilder a general purpose tool is not a business priority.  Addressing this would not add value to the .NET usage of the tool.
