### ISSUE TITLE
Publish stage of pipeline always publishes readmes and manifest

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#371]
The task for publishing readmes in the publish stage of the pipeline is configured to always execute, even if the build is configured with a `test` repo prefix.  This means that test builds can inadvertently update production readmes.  The task is configured to conditionally run only if the `publishReadme` variable is true but that appears to be always set to true.

Similarly, the task to publish the manifest is always executed in the same manner.

Ideally, the build should continue to execute the tasks but with a `--dry-run` option to prevent any side effects.  The `publishMcrDocs` command in ImageBuilder doesn't seem to honor that option in this case so that will need to be updated as well.  The `publishManifest` command does honor the `--dry-run` option.

**Comment by mthalman** [comment]
@MichaelSimons - I think actually it is probably ok for the `publishManifest` command to be run even on test builds.  That will allow the manifest tags to be accessible if making use of the internal publish location, for whatever reason.  It's also better to more fully execute the pipeline when possible.  Since there's no negative consequences of running this, it might as well be done.  Agreed?

**Comment by MichaelSimons** [comment]
Yes, I will use stronger wording through.  The `publishManifest` command is required for our test builds because we need to have the mult-platform tags generated for testing purposes.
