### ISSUE TITLE
Eliminate tribal knowledge of release process and automate as much as possible

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/docker-tools#382]
We currently have good build automation as well as automation that updates the Dockerfiles with the specified components.  We don't however have a fully automated release process.  The release process today involves prepping the PRs in the master branches.  This may involve manually running the update-dependencies tools or merging changes between branches.  The PRs must be manually merged and then the builds are queued across the repos in the correct order.

We should have release pipelines that can be used to release the Docker images.  There are two main release scenarios to consider.

1. .NET Core product release
1. PT release

The .NET Core product release should be tied into the main .NET Core product release.  The PT release would involve both the .NET Core and .NET Fx repos.

As part of this effort, we should consider creating scripts for the activities the repo maintainers perform.  For example create a script that codifies the invocation of update-dependencies to create a release PR.

**Goals:**

1. The Docker image release process is streamlined to reduce human error.
1. It takes less time from start to finish to complete the release.
1. It is relatively easy for anyone to execute the release process.  The release doesn't involve manual steps which require tribal knowledge of what to do.

**Comment by mthalman** [comment]
[Triage]
The work for this is generally implemented at this point. There's some other more specific issues that exist to help improve things. But the overall desire of this has been met.
