### ISSUE TITLE
Refactor GetStaleImageCommand to not have a dependency on the image info

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/docker-tools#393]
The primary reason to eliminate external dependencies.  It is possible the image info can be out of date.  [Here](https://github.com/dotnet/docker-tools/pull/389) is an example of this.  

The published images should always be considered the source of truth.  We can pull the .NET Core image manifests and compare them with the base image manifests.

**Comment by mthalman** [comment]
[Triage]
The image info JSON file is the only source for the base image digest information. The published image/manifest doesn't indicate at all what the base digest is. So we can only rely on the JSON file. In the future we may be able to use OCI annotations to store in the registry the base image digest associated with the image and that could be used instead. But that's not implemented yet.
