### ISSUE TITLE
Implement a monitoring solution for image publishing

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/docker-tools#394]
The only option that exists today for monitoring the infrastructure used during image production, is to subscribe to the AzDO pipeline notifications.  This is not a user friendly solution as you need to inspect the builds to see things like the queue parameters, etc.  This has to be done for numerous different builds.  It is difficult and time consuming to do this type of monitoring and as a result, I postulate we are not doing the best of job.  A recent occurrence which we missed via monitoring is https://github.com/dotnet/docker-tools/pull/389.

To solve this problem, it would be nice to have a monitoring solution that would give a high level overview of what is happening.  Examples include:

* Base image change notification and the images that need to get rebuilt as a result.
* Image publishing notification
* ACR cleanup notification - how much space was freed and how much space is being used.
* etc.

I don't think an elaborate system is needed.  It should be simple and cheap to build (e.g email a DL).  It can be refactored and expanded as necessary.

**Comment by MichaelSimons** [comment]
We feel this is an important issue to address as we should have more visibility into what is happening within the builds.  Assigning to @mthalman to investigate sending a notification/email from within the build.

**Comment by mthalman** [comment]
AzDO has no native solution for sending emails and dnceng isn't aware of any existing pipelines in the org that do this.  Our best bet might be to make use of [SendGrid](https://docs.microsoft.com/en-us/azure/sendgrid-dotnet-how-to-send-email) in Azure.  They have a free service tier that should be sufficient.

**Comment by mthalman** [comment]
[Triage]
The current solution we have for notifying of publishing and rebuilds gives us visibility into the state of the image publishing infrastructure. For image cleanup, the clean up pipeline also reports on what has been cleaned up. At this point, investing in anything beyond this isn't worth it.
