### ISSUE TITLE
PublishImageInfoCommand should remove out of date image info

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/docker-tools#436]
The [current Image Info data](https://github.com/dotnet/versions/blob/master/build-info/docker/image-info.dotnet-dotnet-docker-master.json) for the .NET Docker repos contains image info for images that are no longer supported e.g. .NET Core 2.2 and 3.0).  The PublishImageInfoCommand should be removing the image info once an image reaches EOL.  The Manifest file is the source of truth so any image in the image info that is not in the manifest should be removed.

**Comment by mthalman** [comment]
This logic needed to be temporarily disabled due to it corrupting the image info content: https://github.com/dotnet/docker-tools/issues/436.  Need to get this fixed and re-enabled.
