### ISSUE TITLE
Store base image digest for internally built base images

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#447]
In the image info file, there's a field to stored the digest of the base image.  This is only retrieved for a base image that is external to the .NET images.  Right now, it attempts to retrieve the digest but it ends up being null because the base image hadn't yet been pushed.

In the interest of providing full fidelity of information on the images, it would be good to include base image digests for those base images that have been built internally as well.  This provides us an easy way to correlate image dependencies.

**Comment by MichaelSimons** [comment]
Closing - We can't think of a strong use case for this information.
