### ISSUE TITLE
Store fully-qualified digest in image info

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#448]
The `Digest` value in the image info file is currently just the SHA value.  From a usability perspective, it would be beneficial to store the fully-qualified digest value (i.e. registry/repo:sha) to assist in retrieving the image by its digest.  Currently, you'd have to know what the registry is since it's not stored in the image info file, and then track down the associated repo name that it's contained within.

Storing this is complicated by the fact that the fully-qualified digest value that is returned by Docker is not the MCR location but rather than ACR staging location.  But we actually want to store the eventual MCR location.

**Comment by MichaelSimons** [comment]
The uses cases for this are limited.  You can figure the fully qualified digest given the context.
