### ISSUE TITLE
Add checked in definitions for version monitor builds

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/docker-tools#45]
Consider adding checked in definitions that are used for detecting changes to base images.

https://devdiv.visualstudio.com/DevDiv/_build/index?context=mine&path=%5Cdotnet-docker&definitionId=7154&_a=completed
https://devdiv.visualstudio.com/DevDiv/_build/index?context=mine&path=%5Cdotnet-docker&definitionId=7116&_a=completed

**Comment by dleeapho** [comment]
Either Jenkins groovy or VSTS pipebuild depending on the state of the transition.

**Comment by MichaelSimons** [comment]
This is being addressed by #59
