### ISSUE TITLE
Consider generating image info file in PR build

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#474]
Currently, PR builds do not generate an image info file since it's not desired to have one published to an external repo for such builds.  But this exposes a hole in the workflow because it's not executing logic that would get executed in the official builds.  There have been numerous cases where issues related to image info have occurred in official builds that could have been caught if the PR build had generated one.

I propose that PR builds follow the same workflow for generating an image info file except for the task of actually publishing it to an external repo.

**Comment by MichaelSimons** [comment]
The broader issue here is that we should be running as much of the publish leg as possible without publishing the images.  This helps surface issues in PR validation.
