### ISSUE TITLE
Use aarch64 version of AzDO agent

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#486]
The current infrastructure for supporting Linux ARM builds has been to use a Linux AMD64 agent machine that sends remote Docker commands to an aarch64 machine.  This was necessary because the AzDO agent software didn't support aarch64.  But now that a release candidate is available for this support (https://github.com/microsoft/azure-pipelines-agent/issues/1911), we can update the infrastructure so that the Linux AMD64 agent machine goes away and the aarch64 machine directly runs the agent software.

- [x] Publish an ARM version of [Image Builder](https://github.com/dotnet/docker-tools/blob/master/src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux) with a multi-arch tag
- [x] Publish an ARM version of the [Test Runner](https://github.com/dotnet/docker-tools/blob/master/src/Microsoft.DotNet.ImageBuilder/Dockerfile.linux.runner) image with a multi-arch tag
- [x] Update common pipeline logic to consume multi-arch tags for Image Builder and Test Runner
- [x] Update common pipeline logic to conditionally support ARM agents
- [x] Install agent software on public ARM machines
- [x] Disable use of remote Docker server in common pipeline logic in nightly branch
- [x] Test for a period of time to ensure builds are working
- [ ] Install agent software on internal ARM machines
- [ ] Disable use of remote Docker server in common pipeline logic in master branch
- [ ] De-allocate AMD build agents used w/ARM machines

**Comment by MichaelSimons** [comment]
We should do this.  We should be scouting and providing feedback.  We should role this out to CI first to ensure stability.

**Comment by mthalman** [comment]
I've sent an email to DDFUN to get this process started.

The proposed process is to start by rolling this out to a single ARM machine in the public CI pool.  That will determine whether it's even possible to have something working.  If that works, we'll roll it out to the rest of the ARM machines in the public pool.  Once we've determined that things are stable there, we'll roll it out to the internal build machines.

**Comment by MichaelSimons** [comment]
@mthalman, Any update on the roll out?

**Comment by mthalman** [comment]
It's been on hold for a few weeks due to other higher priority work.  I've verified that the ARM version of the agent software does in fact work; I was able to run builds directly on the ARM machine.  The next step is to start producing ARM versions of Image Builder since it'll now need to be executed directly on ARM hardware.

**Comment by mthalman** [comment]
I'm finished with the prototype and have verified that this should work.  I've updated this issue with the set of steps to take to implement this.

**Comment by MichaelSimons** [comment]
Thanks for the update @mthalman. I added one step to ensure the deallocation of the AMD build agents used w/the ARM machines.

**Comment by mthalman** [comment]
Status update:
I've run a full test build on ARM legs using the single build agent that's been configured and everything works.  This makes use of the multi-arch tags of the Image Builder and Test Runner images.

I've created a ticket to get the machine configuration changes rolled out to the rest of the Jetson machines in the Dotnet-Docker-Public agent pool.

**Comment by mthalman** [comment]
Jetson machines have all been updated and tested.  Pipeline changes are in the process of rolling out to the repos so that the new configuration is supported.

**Comment by mthalman** [comment]
After a couple weeks of testing, it appears the updated agents are working without issue.  I've logged a ticket to get these configuration changes rolled out to the internal build agents.
