### ISSUE TITLE
Consider including full build version in tags table for Windows images

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#488]
The tags table in Docker Hub currently shows the version of Windows image as the brand version (e.g. 1903, 1909, etc).  It would also be helpful to display the full build version (e.g. 10.0.14393.3630) so that it can be quickly referenced without someone needing to inspect the container.  An example of a scenario for this is https://github.com/microsoft/dotnet-framework-docker/issues/558#issuecomment-617807587.

**Comment by MichaelSimons** [comment]
After discussion we feel this belongs in the ["tags details" feature](https://github.com/dotnet/dotnet-docker/issues/212) that is on the backlog.
