### ISSUE TITLE
Investigate using Ubuntu 18.04 for Linux builds

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#538]
Currently the Linux build legs are configured to use [Ubuntu 16.04](https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1604-README.md) as the VM image.  I've read some articles stating that there are scenarios where performance is significantly better using Ubuntu 18.04 compared to 16.04.  We should do some testing using the [18.04](https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md) VM image and see how it compares.

**Comment by mthalman** [comment]
I've done some test builds using Ubuntu 18.04 and found it to be slightly better, nothing drastic.  It's about a 5% reduction in overall build times.

**Comment by MichaelSimons** [comment]
5% seems worthwhile as often as the images are built.  It is a pretty simple change isn't it?  You just have to change the build pool name?  Is there anymore "investigation" work to do under this issue?

**Comment by mthalman** [comment]
Yes, I agree it's worthwhile to do.  It's not as simple as changing the pool name.  It instead needs to specify the `vmImage` property instead of `name`:

```yml
pool:
  vmImage: ubuntu-latest
```

That may slightly complicate things because of the need to accomodate dotnet-buildtools-prereqs-docker to specify a custom pool/queue: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/65dfcd6658bb27785a2b4ad437a48daa01ee1b8a/eng/pipelines/dotnet-buildtools-prereqs-eng.yml#L24.
