### ISSUE TITLE
COGS Dashboard

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#539]
We currently don't have a good picture of what our COGS are day-to-day/month-to-month.  For that reason, it can be difficult to report on some of the cost savings that have been made with the infrastructure.  We can maybe report on absolute savings but there's not a way to express that in terms of relative savings compared to our total costs.

The proposal is to collect and report on data that reflects the COGS for producing the .NET Docker images.  This would be useful for work like https://github.com/dotnet/docker-tools/issues/532, where it would provide an indication of the relative COGS savings.

Metrics to track:

- Number of build agents
- Build agent cost
- Build agent compute hours
- ACR storage usage 
- ACR storage cost

**Comment by MichaelSimons** [comment]
The _Build agent compute hours_ is now being tracked in the .NET Docker Power BI dashboard.

**Comment by mthalman** [comment]
[Triage]

These items seem to be relevant for dnceng or ddfun to have ownership of because its usefulness would be relevant to all teams, not just Docker:

* Number of build agents
* Build agent cost
* Build agent compute hours
