### ISSUE TITLE
Add validation in build command to prevent inadvertent pulls

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#592]
There have been cases where bugs in the infrastructure have resulted in the implicit pulling of images during a `docker build` command.

Example from https://github.com/dotnet/dotnet-docker/issues/2090:
```
-- EXECUTING: docker build -t mcr.microsoft.com/dotnet/core-nightly/aspnet:3.1.6-alpine3.12 -t mcr.microsoft.com/dotnet/core-nightly/aspnet:3.1-alpine3.12 -t mcr.microsoft.com/dotnet/core-nightly/aspnet:3.1.6-alpine -t mcr.microsoft.com/dotnet/core-nightly/aspnet:3.1-alpine -f src/aspnet/3.1/alpine3.12/amd64/Dockerfile --build-arg REPO=mcr.microsoft.com/dotnet/core-nightly/runtime src/aspnet/3.1/alpine3.12/amd64
Sending build context to Docker daemon   2.56kB

Step 1/3 : ARG REPO=mcr.microsoft.com/dotnet/core/runtime
Step 2/3 : FROM $REPO:3.1-alpine3.12
3.1-alpine3.12: Pulling from dotnet/core-nightly/runtime
df20fa9351a1: Already exists
ed937d6b1c19: Pulling fs layer
ab29de8d4074: Pulling fs layer
ed937d6b1c19: Verifying Checksum
ed937d6b1c19: Download complete
ed937d6b1c19: Pull complete
ab29de8d4074: Verifying Checksum
ab29de8d4074: Download complete
ab29de8d4074: Pull complete
Digest: sha256:42e51005c7ed9d42a193744d116b6e81bb68faef1e3afd1a39530fdd60aa8db1
Status: Downloaded newer image for mcr.microsoft.com/dotnet/core-nightly/runtime:3.1-alpine3.12
 ---> c255a55d06e7
```

A pull should never occur implicitly when we run a `docker build` command since our intent is to have all dependent images pre-pulled before building.  The impact of this is that the image gets built based on an unintended source.  Even more problematic is that there's nothing that alerts us of this problem.  The image gets pulled and as long as the build and tests pass, we don't notice.  But this kind of behavior is not correct and can lead to very wrong results.

By adding logic to Image Builder's `build` command, we can parse the standard output and look for any occurrences of `Pulling from` in the output and throw an exception in that case.  This will ensure we are aware of the issue right away.

This logic should also be included in test runs to ensure we don't pull images inadvertently during tests.

**Comment by MichaelSimons** [comment]
@mthalman - Is this fixed by #593?
