### ISSUE TITLE
Disallow builds from non-official branches by default

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#605]
In order to help prevent the unintentional publishing of images that are not meant to be public, we should consider there being a validation check in the publish stage that will fail the build if it's occurring on a non-official branch and the publish destination is "public".

I think this should only be a check within the publish stage because it is still useful to sometimes prep images from a non-official branch.  But once time comes to publish, it should be from an official branch.

**Comment by MichaelSimons** [comment]
Yes, this is a good suggestion and should be implemented soon.

**Comment by mthalman** [comment]
Based on the resolution of https://github.com/dotnet/docker-tools/issues/650, the decision is to apply this across for the board for any stage of a build, not just publish.
