### ISSUE TITLE
Ensuring published images are up-to-date with latest base images

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#609]
When publishing images it's important that they are up-to-date w.r.t. the latest base images that they're dependent on.  This is important because it avoids rebuilding images when it's been determined that they are not up-to-date.  The goal should be to have as few image publishing events as possible because it incurs infrastructure cost for us and those downstream consuming our published images.  A couple scenarios to consider that can violate this principle:

### Released images not up-to-date

1. A build is run with just the Build stage of the pipeline to prep for a release and builds an Ubuntu Focal image graph (runtime-deps, runtime, aspnet, sdk).  At the time of the build runtime-deps is based on version X of Ubuntu Focal.
2. Ubuntu Focal images get updated to version Y.
3. Image release continues by running the test and publish stages of the pipeline using the images built from step 1.  Images get published.  These images are still based on version X of Ubuntu Focal.
4. Later on in the day, our infrastructure detects that the images are not up-to-date because they're not based on version Y of Ubuntu Focal.  Another build is kicked off to rebuild the images so they're up-to-date.

Net result is that images were initially released that were not up-to-date.  A subsequent build updated them resulting in two image updates for the release.

### Released images replace updated images

1. A build is run with just the Build stage of the pipeline to prep for a release and builds an Ubuntu Focal image graph (runtime-deps, runtime, aspnet, sdk).  At the time of the build runtime-deps is based on version X of Ubuntu Focal.
2. Ubuntu Focal images get updated to version Y.
3. Our infrastructure detects that the currently released images are not up-to-date because they're not based on version Y of Ubuntu Focal.  A build is kicked off to rebuild the images so they're up-to-date.
3. Image release continues by running the test and publish stages of the pipeline using the images built from step 1.  Images get published.  These images are still based on version X of Ubuntu Focal and end up replacing the images that were published from step 2.
4. Later on in the day, our infrastructure detects that the images are not up-to-date because they're not based on version Y of Ubuntu Focal.  Another build is kicked off to rebuild the images so they're up-to-date.

Net result is that images were initially released that were not up-to-date.  A subsequent build updates them.  But there are a total of 3 publish events for these images that occur in the day.

We should consider options for preventing this behavior.

**Comment by MichaelSimons** [comment]
We are unaware of this ever being an issue before.  A different approach would be to disable the automated builds triggered by base image changes during the release window.  The benefit this would have is that it would avoid releasing images multiple times.

@mthalman - Can you update the title and description to describe the theoretical problem and then we can enumerate and discuss the solutions.

**Comment by mthalman** [comment]
I've updated the description to describe two scenarios that cause the general problem of ending up with released images not being up-to-date.

**Comment by MichaelSimons** [comment]
This something to be on the lookout for but the likelihood of encountering it is low.  This is low in priority so we are going to close the issue.
