### ISSUE TITLE
Remove temp logic to handle image info digest values that aren't fully-qualified

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#611]
Temporary logic is being added by https://github.com/dotnet/docker-tools/pull/610 to handle cases where the digest values stored in image info files are not fully-qualified (i.e. they contain only the SHA value).  This logic should be removed once all these values get overwritten from subsequent publishes that will replace the digests to be fully-qualified.

**Comment by MichaelSimons** [comment]
The repo that is holding this up is dotnet-buildtools-prereqs.  The specific issue is https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/229.
