### ISSUE TITLE
Mitigate Docker manifest request rate limiting

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#613]
Docker has [announced](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/) new rate limits for manifest requests.  The rate limits take effect Nov. 1, 2020.

> Free plan – anonymous users: 100 pulls per 6 hours 
> Free plan – authenticated users: 200 pulls per 6 hours
> Pro plan – unlimited
> Team plan – unlimited

Currently, our infrastructure makes these requests anonymously so it would be limited to 100 requests per 6 hrs.  However, even the 200 request limit is likely to problematic for some of our scenarios.

There needs to be a plan for mitigating this rate limit.

**Comment by mthalman** [comment]
Current POR:

* We should get a paid account to be used by our bot.  This will eliminate any possibility of encountering the rate limit.
* We should mirror the images we depend on from Docker Hub into our ACR.  We shouldn't be reliant on the availability and operation of a third party service in order to publish our images.
* Mirroring should be done periodically by the base image monitoring system.
* Any time an official build is started, it should first trigger a mirroring update.  If mirroring fails, the build can still continue.

**Comment by mthalman** [comment]
Tasks:

- [ ] ImageBuilder command to mirror images
- [ ] Scheduled pipeline to run command to mirror images
- [ ] Dynamically rewrite Dockerfiles at build time to target mirror location
- [ ] Use paid account for connecting to Docker Hub

**Comment by MichaelSimons** [comment]
@dleeapho, What is the status of getting a Docker Hub account for us to use?

**Comment by mthalman** [comment]
A Docker Hub account is now available so I'll start work on updating our pipelines to use that.
