### ISSUE TITLE
CommitUrl diffs when image is built from feature branch

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#650]
The image caching feature relies on the CommitUrl field defined in the image info file in order to determine whether to retrieve a cached image.  There are problems with this value depending on how the images were built.  This can lead to diffs in the value resulting in incorrect cache misses.

An example of this was the recent 9B release for the .NET Fx images (https://github.com/microsoft/dotnet-framework-docker/issues/634).  In that release, the images were optimistically built from a feature branch while the PR was under review and validating.  Prior to publishing those images, the PR was merged.  The build to publish the images was then run from the master branch.  The problem with this workflow is that the image info gets populated with the commit SHAs from the feature branch.  Let's call this SHA X.  The image info that gets published contains SHA X.  When the PR gets merged to master, a new SHA gets calculated: SHA Y.  When a subsequent build runs that theoretically should take advantage of caching, it will get a cache miss because the SHA that is retrieved from the build is SHA Y which differs from the SHA X in the image info file.

One solution to this problem is to defer the populating of the CommitUrl field in the image info until the publish stage instead of in the build stage.  This works as long as two conditions are met:
1. We only publish from an official branch, not a feature branch.  This will be enforced by https://github.com/dotnet/docker-tools/issues/605.
2. There are no subsequent commits that change the Dockerfiles to be built between the time when the build stage runs and the publish stage runs.  In that case, the commit SHA is not representative of the version of the Dockerfile that was built.  This would be a bad practice in general but needs to be called out.

The alternative is to change our workflow to never build images in a feature branch for an official release.  The advantage of using a feature branch is that it expedites the delivery of images by optimistically getting the images pre-built while further validation of the changes is ongoing.

**Comment by MichaelSimons** [comment]
Decision is to make PR, allow one PR validation leg to complete as a smoke test, merge the PR, and then trigger the official build off of master.  

With this plan, no changes are needed - closing.
