### ISSUE TITLE
Improve the readability of the build script output for the dev workflow

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/docker-tools#680]
The readability of the using build script output for the dev workflow is not great.

The following is the output from building the dotnet-docker samples using `.\build-and-test.ps1 -Paths samples* -TestCategories pre-build, sample`

[https://app.zenhub.com/files/89951797/edee9818-6e73-4276-8f7f-91af4be26182/download](https://app.zenhub.com/files/89951797/edee9818-6e73-4276-8f7f-91af4be26182/download)

There is one obvious part that is a major culprit.  The output of running `manifest-tool inspect xxx --raw` is appearing.  This is a single line but gets wrapped in the shell to be 100's if not 1000's of lines long.  This makes scrolling through the build output to see the beginning difficult.

The build output should be readable so the the developer can easily decipher what is happening.

**Comment by mthalman** [comment]
[Triage]

The use of the manifest-tool has been removed so it's not contributing to this output anymore. Closing as there are no major known output issues with the build output at this point.
