### ISSUE TITLE
Remove dependency on sac2016

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#721]
Currently Image Builder uses `nanoserver:sac2016` which is out of support.  There are several options we can consider to handle this.

1. **Reference Server Core 2016 instead**.  This would seemingly be the proper thing to do but there are issues with that.  The image for `servercore:ltsc2016` is incredibly large (5.7 GB).  This is problematic primarily for developer scenarios. Because Docker images are often purged on a developer machine, it would require pulling a lot of data just to pull the Image Builder image.  It would also impact the [scale set build agents](https://github.com/dotnet/docker-tools/issues/532) because those machines would need to also have `servercore:ltsc2016` pre-pulled in the VM image in order to be viable.
2. **Store the Windows version of Image Builder bits on some storage location like a nupkg or blob storage (see https://github.com/dotnet/docker-tools/issues/67)**.  This works because, on Windows environments, we're essentially using Docker containers as a storage device to copy the Image Builder exe out of and run it on the host machine.  This is done because  Windows Server 2016 containers are the only supported version that don't support the Docker-in-Docker feature that we make use of for the Linux version of Image Builder.  Since we can't use Docker-in-Docker, we need to copy the exe out of the container.  If it was located on some external download location, we could just use that instead and not even bother with a Windows container.
3. **Produce Windows version-specific images of Image Builder.**  This would create multiple versions of Image Builder for each supported Windows version.  There would separate tags for each of those versions, all wrapped up in the manifest list tag we already generate.  This solves the problem because the other versions can use Nano Server and we can just use Server Core for the 2016 version.  For dev machines, they'll be on more recent versions of Windows so pulling the manifest tag will provide a small Nano Server image.  Only on the Windows Server 2016 build machines would the Server Core image be pulled but it will already have that image pulled.
4. **Reference Nano Server 1809 instead.**  The reason we currently reference Server 2016 for the Image Builder image is because we use Server 2016 host machines to build our 2016 images and so we need a version of Image Builder that can run on a 2016 host machine.  We could instead use Server 2019 host machines to build 2016 images through the use of Hyper-V isolation to handle the container version compatibility.  We would need to measure the performance of this to determine if that would slow things down too much.  That would mean we could get rid of our Server 2016 build agents and just use 2019 as the "minimum" version.

**Comment by mthalman** [comment]
The POR is to use option 4: reference Nano Server 1809 instead.  This requires the ability to build Server 2016 images on 1809 host machines.  This is done by using hyperv isolation.  I've tested that out and works in some case but fails in others due to running out of storage space in the container during docker build.  It seems reasonable that using Hyper-V requires more storage space.  We need to wait for https://github.com/moby/moby/pull/41636 to be rolled out before we can get this to work I think.

**Comment by MichaelSimons** [comment]
> Another option is to produce multiple versions of Image Builder targeted at different Windows versions:

Is this alternative option any different than option #3 in the original description?

**Comment by mthalman** [comment]
Ah, I guess not.  🙂  They're the same thing.

**Comment by MichaelSimons** [comment]
[Traige] We need to implement some type of fix in order to stop using the unsupported sac2016 images.  Option #3 seems reasonable given the blocking Docker issue with #4.
