### ISSUE TITLE
Remove unused project Microsoft.DotNet.ImageBuilder.Tests

### ISSUE THREAD

**Issue by ravimeda** [dotnet/docker-tools#77]
Remove unused project `Microsoft.DotNet.ImageBuilder.Tests` from `Microsoft.DotNet.ImageBuilder.sln`

Refer to https://github.com/dotnet/docker-tools/blob/master/Microsoft.DotNet.ImageBuilder/Microsoft.DotNet.ImageBuilder.sln#L7

**Comment by MichaelSimons** [comment]
This is work in progress - see #8.  Test implementation should be completed instead of removing the project.
