### ISSUE TITLE
Stale layer data being stored in image info files

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#772]
The image info files being stored in the dotnet/versions repo has a `layers` array for each platform that keeps collecting layer IDs cumulatively with each build.  Example: https://github.com/dotnet/versions/commit/6d04fab6e1555d8aab1f95975982b202b420a453#diff-40dc95d8fe0560920bc22d0badcea796de27dbf61ae66e7acfb045606b790bb8R6820-R6848

This is because the layers from a build are being merged into the existing array rather than replacing it.  The merging of image info data should use the replacement option for layers just as it does for tags.  See:

https://github.com/dotnet/docker-tools/blob/f6dd63ae06f468cf0d450f506971fb1d2d9e4b71/src/Microsoft.DotNet.ImageBuilder/src/ImageInfoHelper.cs#L159-L181

**Comment by MichaelSimons** [comment]
Fixed with https://github.com/dotnet/docker-tools/pull/774
