### ISSUE TITLE
Support caching behavior by path

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#787]
Currently the build infra has a single setting which can be used to disable the image caching behavior: `noCache = true`.  Since the scope of that variable applies to all the Dockerfiles included in the build, it can end up including Dockerfiles that should take advantage of caching.

As an example, if https://github.com/dotnet/dotnet-docker/issues/1455 were to be implemented, there could be scenarios where a package update is necessary in the `sdk` image, such as `curl`. In that case a build would be queued with caching disabled. Only the `sdk` image actually needs to get rebuilt but because caching is disabled, it would cause the entire image hierarchy (`runtime-deps`, `runtime`, `aspnet`) to also get rebuilt.  This is unnecessary and wasteful both for build time and image storage.  Having a way to indicate that caching should only be disabled for the `sdk` Dockerfile would solve this issue.

Are there other scenarios outside of https://github.com/dotnet/dotnet-docker/issues/1455 where this functionality could be useful or should it just be considered as part of the implementation for that issue?

**Comment by MichaelSimons** [comment]
[Triage] We need more data in the space of triggering builds to pickup package updates outside of our normal builds/servicing.  We know we will benefit from this infra but what is the impact of not having it?

**Comment by mthalman** [comment]
[Triage]
This situation is mostly relevant to the case of needing to rebuild just the sdk but not the entire image graph because that is the image which has additional packages installed beyond what is in runtime-deps. The need to do this doesn't come up that often. It's basically limited to CVEs occurring in one of the packages we install only in the sdk. That occurs maybe once every few months.

The cost associated with this is going to be pretty high and doesn't provide that much substantial benefit given the low number of cases per year that we need this. Closing.
