### ISSUE TITLE
Provide detailed tag info

### ISSUE THREAD

**Issue by ravimeda** [dotnet/docker-tools#79]
## Steps to reproduce the issue
1. I would like to try out the .NET Core SDK Docker image. So, I visit https://hub.docker.com/r/microsoft/dotnet/
2. I try to get image details such as the Dockerfile that was used to assemble the image, the version of .NET Core SDK and Shared Framework available on the image.

## Expected behavior

Detailed tag information is available.  Information should include -

- Dockerfile. Not just a link to latest version. But the specific version (commit) that was used to build the image
- Platforms
- Layers 
- Date-time when the image was created
- Docker version that was used to assemble the image

Similar to https://github.com/docker-library/repo-info/blob/master/repos/golang/remote/windowsservercore-1709.md

## Actual behavior

Only a link to the latest Dockerfile is posted. For example,  https://github.com/dotnet/dotnet-docker/blob/master/2.0/sdk/nanoserver-1709/amd64/Dockerfile

**Comment by ravimeda** [comment]
Updated title and description to more accurately describe the issue.

**Comment by mthalman** [comment]
This is the tooling issue associated with https://github.com/dotnet/dotnet-docker/issues/212, which had been [closed](https://github.com/dotnet/dotnet-docker/issues/212#issuecomment-1371334509). The same applies to this issue that we have no plans to implement this.
