### ISSUE TITLE
Internal build with non-`public/` `publishRepoPrefix` fails to build because base image weren't mirrored

### ISSUE THREAD

**Issue by dagood** [dotnet/docker-tools#827]
## Steps to reproduce the issue
1. Set up an internal repo and pipeline that uses `eng/common` to build Docker images using ImageBuilder.
2. Build with `publishRepoPrefix` set to `dev/`. (I believe anything other than `public/` will trigger the issue.)

## Expected behavior
Build succeeds.

## Actual behavior
Build fails when trying to build images: it's unable to pull the mirrored base image tags, because they weren't actually mirrored. 😄 The mirror step ran in dry run mode.
https://dev.azure.com/dnceng/internal/_build/results?buildId=1280584&view=logs&j=9aada89a-2e24-5acb-2807-6900158b9cce&t=8a5c5de1-6edd-585e-0d15-1a05f0b96a40&l=115

## Additional information
This line sets `--dry-run`, which makes the "copy base images" step earlier in the build not copy anything:

https://github.com/dotnet/docker-tools/blob/7f59365dd99faff417457f5042a24db373553e4f/eng/common/templates/steps/set-dry-run.yml#L5-L6

But the build still uses `--source-repo-prefix` based on a looser condition:

https://github.com/dotnet/docker-tools/blob/7f59365dd99faff417457f5042a24db373553e4f/eng/common/templates/jobs/build-images.yml#L66-L67

I would guess the `--source-repo-prefix $(mirrorRepoPrefix)` bit should be extracted from that line and put into its own `if` based on `set-dry-run.yml`, so these two parts of the build are in sync.

I hit this when trying to set up a new build pipeline/ACR, but I think it could also happen in dotnet/dotnet-docker if:
1. Someone tries adding a new platform that requires new, never-mirrored-before base images.
2. They run an experimental internal build that pushes to a custom `publishRepoPrefix`.

**Comment by mthalman** [comment]
I think the right way to handle this is for copyBaseImages to ignore `dryRunArg` if it's an internal build.  In other words, if it's an internal build, we should always mirror the images, regardless of the `publishRepoPrefix` value.
