### ISSUE TITLE
"Test Images" in PreBuildValidation assumes `testScriptPath` variable is defined

### ISSUE THREAD

**Issue by dagood** [dotnet/docker-tools#830]
https://github.com/dotnet/docker-tools/blob/7f59365dd99faff417457f5042a24db373553e4f/eng/common/templates/steps/test-images-linux-client.yml#L44-L51

If my repo doesn't have tests yet, I'm not sure what to do with this variable. To get things moving, I added:
```
condition: and(succeeded(), ne(variables['testScriptPath'], ''))
```

**Comment by mthalman** [comment]
If there are no tests, then the test stage can be skipped.  This would be done by not including `test` in the `stages` variable.  So `stages` would just be set to `build;publish`.

**Comment by mthalman** [comment]
Oh, but you're running into this in PreBuildValidation I see.  Ok, yeah.  I see the problem.

**Comment by dagood** [comment]
> If there are no tests, then the test stage can be skipped. This would be done by not including `test` in the `stages` variable. So `stages` would just be set to `build;publish`.

Just to confirm: yep, already have it set to `build;publish`. (So I suppose conditioning this step on that variable instead of `ne(variables['testScriptPath'], '')` would work too.)
