### ISSUE TITLE
What does `acr.servicePrincipalName` (etc.) mean in `copyAcrImages` for Publish?

### ISSUE THREAD

**Issue by dagood** [dotnet/docker-tools#831]
Generally speaking, I don't understand these variables:

https://github.com/dotnet/docker-tools/blob/7f59365dd99faff417457f5042a24db373553e4f/eng/common/templates/jobs/publish.yml#L35-L50

They come from the DotNet-Docker-Common and DotNet-Docker-Secrets variable groups. I'm not sure how to get the values for a different ACR.

(In general, setup documentation would be helpful. But this is a particularly tricky part: secrets that involve AzDO/Azure are particularly hard to investigate as a new dotnet/docker-tools user because of lack of permissions. The other parts can generally be figured out by looking at how .NET Docker uses the tooling and has the build pipeline set up.)

**Comment by MichaelSimons** [comment]
Creating pipeline configuration documentation is something we are already tracking with #733.
