### ISSUE TITLE
Templates in eng/common use `BotAccount-dotnet-docker-acr-bot-password` variable directly by name

### ISSUE THREAD

**Issue by dagood** [dotnet/docker-tools#833]
https://github.com/dotnet/docker-tools/blob/7f59365dd99faff417457f5042a24db373553e4f/eng/common/templates/jobs/build-images.yml#L67

https://github.com/dotnet/docker-tools/blob/7f59365dd99faff417457f5042a24db373553e4f/eng/common/templates/jobs/publish.yml#L55

https://github.com/dotnet/docker-tools/blob/7f59365dd99faff417457f5042a24db373553e4f/eng/common/templates/steps/test-images-linux-client.yml#L38

https://github.com/dotnet/docker-tools/blob/7f59365dd99faff417457f5042a24db373553e4f/eng/common/templates/steps/test-images-windows-client.yml#L8

This is actually easy to work around using a variable, but it isn't great when reading through the yml: it *appears* we're still using a `dotnet-docker` bot rather than one that's specific to my project:

```yml
- name: BotAccount-dotnet-docker-acr-bot-password
  value: $(my-secret)
```

**Comment by mthalman** [comment]
Duplicate. Closing this in favor of https://github.com/dotnet/docker-tools/issues/843 since that one is more generally defined.
