### ISSUE TITLE
eng/common/build.ps1 `src/*/*/*` filter makes it harder to work with other path styles

### ISSUE THREAD

**Issue by dagood** [dotnet/docker-tools#836]
## Steps to reproduce the issue
1. Add dotnet/docker-tools infra into a repo with an established Dockerfile path style that doesn't have a `src/` root directory.
2. Add manifest.json, etc.
3. Run my build script that calls `eng/common/build.ps1`.

## Expected behavior
The build command will build all my Dockerfiles.

## Actual behavior
The build command has a built-in path filter that excludes all my Dockerfiles (`src/*/*/*`):

https://github.com/dotnet/docker-tools/blob/e7f18726f562a97522eaf71ceaad64b316c6998b/eng/common/build.ps1#L60-L65

## Additional information
In my case, I can change the repo to conform and it doesn't seem like a big problem, although going back to the existing style would be good for browsability for anyone already familiar with the style. (Conforming might not be an option for other projects.)

Letting my script pass in an alternative default filter would let me get around this.

**Comment by MichaelSimons** [comment]
[Triage] An alternative way to eliminate the folder structure coupling the in the script is to add a version filter option that operates against the productVersion manifest metadata.
