### ISSUE TITLE
Execution of PowerShell hook scripts do not fail build command on error

### ISSUE THREAD

**Issue by mthalman** [dotnet/docker-tools#883]
When executing a PowerShell-based pre-build or post-build hook script and that script fails, it won't cause a non-zero exit code and not cause the build command to throw an exception.  The build will incorrectly continue execution.

Relevant code:

https://github.com/dotnet/docker-tools/blob/2dddfe26ef6faca5f110fe1f6c179e47a51f3433/src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs#L580-L609

This is an example of this issue: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/523

**Comment by lbussell** [comment]
Do we still use any hook scripts? Weren't these removed from buildtools-prereqs in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1065? Can we remove this feature from ImageBuilder?

**Comment by mthalman** [comment]
You're correct. It was only used by buildtools-prereqs in the past. And looks like all usage of it has been replaced now.

**Comment by lbussell** [comment]
Closing in favor of https://github.com/dotnet/docker-tools/issues/1377
