### ISSUE TITLE
On Windows, manifest-tool ACR auth appears to work only on Docker pool, not default pool

### ISSUE THREAD

**Issue by dagood** [dotnet/docker-tools#905]
Here's a build using defaults, that fails:
https://dev.azure.com/dnceng/internal/_build/results?buildId=1470163&view=results

```
-- EXECUTING: manifest-tool inspect golangimages.azurecr.io/build-staging/1470163/oss/go/microsoft/alpha/golang:1.15.15-1-windowsservercore-1809-amd64 --raw
time="2021-11-15T21:30:10Z" level=error msg="Error trying v2 registry: Get \"https://golangimages.azurecr.io/v2/build-staging/1470163/oss/go/microsoft/alpha/golang/manifests/1.15.15-1-windowsservercore-1809-amd64\": unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information."
time="2021-11-15T21:30:10Z" level=fatal msg="Get \"https://golangimages.azurecr.io/v2/build-staging/1470163/oss/go/microsoft/alpha/golang/manifests/1.15.15-1-windowsservercore-1809-amd64\": unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information."
```

Here's one that switches to e.g. `Docker-2016-${{ variables['System.TeamProject'] }}`, and succeeds:
https://dev.azure.com/dnceng/internal/_build/results?buildId=1471447&view=results

```
-- EXECUTING: manifest-tool inspect mcr.microsoft.com/windows/nanoserver:1809 --raw
[{"Size":0,"MediaType":"applic...
```

Here's the commit that did the switch, the only change:
https://dev.azure.com/dnceng/internal/_git/microsoft-go-images/commit/e6a5cfd1013bee06e6b2524420ee2a0b8396129e/

---

It looks like `docker login` works differently. In the **failure** case, there are no warnings attached to `docker login`:

```
-- EXECUTING: docker login -u golangimages --password-stdin golangimages.azurecr.io
Login Succeeded
```

In the **success** case, there's a warning:

```
-- EXECUTING: docker login -u golangimages --password-stdin golangimages.azurecr.io
WARNING! Your password will be stored unencrypted in C:\Users\cloudtest\.docker\config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

---

The version data printed at the top of the step is slightly different:

```diff
--- "a/.\\bad.txt"
+++ "b/.\\good.txt"
@@ -1,64 +1,65 @@
 -- EXECUTING: docker version
 Client: Mirantis Container Runtime
  Version:           20.10.7
  API version:       1.41
  Go version:        go1.13.15
  Git commit:        40ef3b6
  Built:             08/19/2021 18:54:26
  OS/Arch:           windows/amd64
  Context:           default
  Experimental:      true
 
 Server: Mirantis Container Runtime
  Engine:
   Version:          20.10.7
   API version:      1.41 (minimum version 1.24)
   Go version:       go1.13.15
   Git commit:       e1bf5b9c13
   Built:            08/19/2021 18:53:20
   OS/Arch:          windows/amd64
-  Experimental:     false
+  Experimental:     true
 -- EXECUTION ELAPSED TIME: 00:00:00.xxx
 -- EXECUTING: docker info
 Client:
  Context:    default
  Debug Mode: false
  Plugins:
   app: Docker Application (Docker Inc., v0.8.0)
   cluster: Manage Mirantis Container Cloud clusters (Mirantis Inc., v1.9.0)
   registry: Manage Docker registries (Docker Inc., 0.1.0)
 
 Server:
  Containers: 0
   Running: 0
   Paused: 0
   Stopped: 0
  Images: 3
  Server Version: 20.10.7
- Storage Driver: windowsfilter
+ Storage Driver: windowsfilter (windows) lcow (linux)
   Windows: 
+  LCOW: 
  Logging Driver: json-file
  Plugins:
   Volume: local
   Network: ics internal l2bridge l2tunnel nat null overlay private transparent
   Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
  Swarm: inactive
  Default Isolation: process
  Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
  Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.2300)
  OSType: windows
  Architecture: x86_64
- CPUs: 2
- Total Memory: 7GiB
- Name: fv-az200-511
- ID: GCDG:LO6D:56KV:BSZU:4KNC:YKTJ:JGAN:YM35:5SIE:24IV:SGRH:73AY
+ CPUs: 8
+ Total Memory: 32GiB
+ Name: 814020f5c000000
+ ID: BDCC:53UQ:AEU5:IC2G:PQIM:QAHG:CVOR:O6RJ:T72C:LFXV:EKF6:U6GU
  Docker Root Dir: C:\ProgramData\docker
  Debug Mode: false
  Registry: https://index.docker.io/v1/
  Labels:
- Experimental: false
+ Experimental: true
  Insecure Registries:
   127.0.0.0/8
  Live Restore Enabled: false
 
--- EXECUTION ELAPSED TIME: 00:00:10.5226831
+-- EXECUTION ELAPSED TIME: 00:00:04.8732980
```

---

My guess: there are two different authentication styles, and the Docker pools are necessary because they use the style that's compatible with `manifest-tool`. "Experimental" mode is the only obvious difference, but I don't know whether there might be some other environment changes in the Docker pools vs. the default pools.

As a workaround, I believe I can just use the Docker pools. @mthalman @MichaelSimons let me know if not.

* Related? #187

**Comment by dagood** [comment]
Background: while upgrading to the latest version of .NET Docker tooling for Go image builds, I tried out the new default pools in the new, more split apart yml templates. I just checked, and I was using the Docker pools before I tried the update, so that's why this suddenly came up.

**Comment by mthalman** [comment]
> In the success case, there's a warning:
> 
> ```
> -- EXECUTING: docker login -u golangimages --password-stdin golangimages.azurecr.io
> WARNING! Your password will be stored unencrypted in C:\Users\cloudtest\.docker\config.json.
> Configure a credential helper to remove this warning. See
> https://docs.docker.com/engine/reference/commandline/login/#credentials-store
> 
> Login Succeeded
> 
> ```

This is the key info, I think. The fact that this warning does not show up in the failure case indicates the credentials are being stored in the native credential store rather than in the config.json file. The [documentation](https://github.com/estesp/manifest-tool/blob/main/README.md#sample-usage) for the manifest tool indicates that it will not use the native credential store. You need to either explicitly pass in the credentials to the tool or have them stored in the config.json file.

My guess is that the Windows VM is configured differently between the pools such that the native credential store is enabled in the hosted pool but not in the custom pool. I don't know if that's a thing that is configurable, just a guess.

**Comment by mthalman** [comment]
Oh, right. That's where the [credential store setting](https://docs.docker.com/engine/reference/commandline/login/#credentials-store) comes into play. It's probably just defined differently between the pools.

**Comment by dagood** [comment]
Maybe it would help people in the future if ImageBuilder could log the credential store settings along with the other Docker version info? (Potentially even warn that this auth issue will come up in the current environment if set differently than expected.)

Or, could ImageBuilder actually set the mode itself, before running `docker login`?

**Comment by mthalman** [comment]
> Maybe it would help people in the future if ImageBuilder could log the credential store settings along with the other Docker version info? (Potentially even warn that this auth issue will come up in the current environment if set differently than expected.)

Logging this seems useful.

Here are the options as I see them:

1. Require the config to have the necessary credential store setting. Warn if it doesn't.
2. Set the credential store setting if it's not set to the required config.
3. Explicitly provide the username/password to the manifest tool.
4. Remove the dependency on the manifest tool and have Image Builder itself make the REST calls to the registry to get the manifest info.

I prefer option 4.

**Comment by mthalman** [comment]
This may be fixed in the new beta version of the manifest tool: https://github.com/estesp/manifest-tool/releases/tag/v2.0.0-beta.1. The release notes contain the following:

> credential helper support built-in

This should be investigated to see if this would resolve this issue.

**Comment by mthalman** [comment]
> This may be fixed in the new beta version of the manifest tool: https://github.com/estesp/manifest-tool/releases/tag/v2.0.0-beta.1. The release notes contain the following:
> 
> > credential helper support built-in
> 
> This should be investigated to see if this would resolve this issue.

I've verified that the 2.0 beta version of the manifest tool works using the native credential store. I'll follow up with the tool owner to see when a release timeframe might be.

**Comment by mthalman** [comment]
Version 2.0 of the manifest tool has been released: https://github.com/estesp/manifest-tool/releases/tag/v2.0.0. Integrating that version into ImageBuilder should resolve this issue.

**Comment by mthalman** [comment]
The update to v2.0 of the manifest-tool is blocked by https://github.com/estesp/manifest-tool/issues/158. It seems unlikely that this will be enabled. We need to determine a way to collect layer digest information to populate our Kusto data.

**Comment by mthalman** [comment]
This should be fixed now by https://github.com/dotnet/docker-tools/pull/998. Querying the manifest is now done using the creds that are passed to the `build` command via the `--registry-creds` option.
